defaults: &defaults
  CONSUMER_KEY: 'q9KLKKbJBD7RtZVMmf167QWnW'
  CONSUMER_SECRET: 'FiM29jFlOErNFGzU44y9MMpSWwPDKAudF7VnLPZG17DM8GEgyx'
  ACCESS_TOKEN: '435149647-ufwxq3A9vg7yVXDJ5EPvmRa7nKRYeiKah2QglwbN'
  ACCESS_TOKEN_SECRET: 'vrnvSGWhBoitjsLVBM1NYsZpUbfPONrJNFNWFQC7NCTd7'

production:
  <<: *defaults